- name: Setup EC2 dev instances for CMMC Compliance
  # Tychon tester node on us-east-2
  hosts: localhost
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        pkg:
        - jq
        - zsh
        - trash-cli
        - gnupg
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl 
        - gnupg  
        - lsb-release 
        state: present
        update_cache: yes
      become: yes
      tags: 
      - test
    - name: Check if AWS CLI installed
      ansible.builtin.shell: aws --version
      register: aws_installed
      ignore_errors: yes
    - name: Download the AWS CLI
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
      when: aws_installed.rc != 0
    - name: Install the AWS CLI
      ansible.builtin.shell: /tmp/aws/install
      when: aws_installed.rc != 0
      become: yes
    # - name: Add Terraform Apt key
    #   ansible.builtin.apt_key:
    #     url: https://apt.releases.hashicorp.com/gpg
    #     state: present
    #   become: yes
    # - name: Add Terraform repository (ubuntu)
    #   ansible.builtin.apt_repository:
    #     repo: deb http://archive.canonical.com/ubuntu focal main
    #     state: present
    #   become: yes
    # - name: Install Terraform
    #   ansible.builtin.apt:
    #     name: terraform
    #     state: present
    #     update_cache: yes
    #   become: yes
    # - name: Download ohmyzsh
    #   ansible.builtin.get_url:
    #     url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    #     dest: /home/ubuntu/ohmyzsh_install.sh
    #     mode: '0645'
    # - name: Install ohmyzsh
    #   ansible.builtin.command: /bin/bash /home/ubuntu/ohmyzsh_install.sh --unattended
    - name: Create a symbolic link for .zshrc
      ansible.builtin.file:
        src: /home/ubuntu/configs/.zshrc
        dest: /home/ubuntu/.zshrc
        owner: ubuntu
        group: ubuntu
        state: link
        force: yes
      tags: 
      - zsh-post-install
    - name: Create a symbolic link for functions.zsh
      ansible.builtin.file:
        src: /home/ubuntu/configs/functions.zsh
        dest: /home/ubuntu/.oh-my-zsh/custom/functions.zsh
        owner: ubuntu
        group: ubuntu
        state: link
        force: yes
      tags: 
      - zsh-post-install
    - name: Create a symbolic link for aliases.zsh
      ansible.builtin.file:
        src: /home/ubuntu/configs/aliases.zsh
        dest: /home/ubuntu/.oh-my-zsh/custom/aliases.zsh
        owner: ubuntu
        group: ubuntu
        state: link
        force: yes
      tags: 
      - zsh-post-install
    - name: Create a symbolic link for aliases.zsh
      ansible.builtin.file:
        src: /home/ubuntu/configs/.vimrc
        dest: /home/ubuntu/.vimrc
        owner: ubuntu
        group: ubuntu
        state: link
        force: yes
      tags: 
      - zsh-post-install